# Generated by Django 6.0.4 on 2026-04-28 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualOutboundOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(editable=False, max_length=30, unique=True, verbose_name='出库单号')),
                ('department', models.CharField(max_length=50, verbose_name='领料部门')),
                ('applicant', models.CharField(max_length=50, verbose_name='领料人')),
                ('employee_id', models.CharField(max_length=20, verbose_name='工号')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('reason', models.TextField(verbose_name='手工领料的原因')),
                ('needs_system_posting', models.BooleanField(default=True, verbose_name='是否需要系统补过账')),
                ('pending_order_numbers', models.TextField(blank=True, help_text='如有多个单号，请用换行分隔', verbose_name='未完成审批的系统领料申请单号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '手工出库单',
                'verbose_name_plural': '手工出库单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManualOutboundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(max_length=30, verbose_name='物料编码')),
                ('material_name', models.CharField(max_length=100, verbose_name='物料描述')),
                ('specification', models.CharField(blank=True, max_length=100, verbose_name='规格')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量')),
                ('unit', models.CharField(max_length=20, verbose_name='单位')),
                ('storage_location', models.CharField(blank=True, max_length=50, verbose_name='存货库位')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('status', models.CharField(choices=[('open', '未关闭'), ('closed', '已关闭')], default='open', max_length=10, verbose_name='状态')),
                ('system_order_no', models.CharField(blank=True, max_length=30, verbose_name='补录系统出库单号')),
                ('close_reason', models.CharField(blank=True, max_length=200, verbose_name='关闭原因')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_items', to=settings.AUTH_USER_MODEL, verbose_name='关闭人')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='outbound.manualoutboundorder', verbose_name='手工出库单')),
            ],
            options={
                'verbose_name': '出库明细',
                'verbose_name_plural': '出库明细',
                'ordering': ['id'],
            },
        ),
    ]
