# Generated by Django 6.0.4 on 2026-04-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualoutboundorder',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交')], default='draft', max_length=10, verbose_name='单据状态'),
        ),
    ]
