# Generated by Django 6.0.4 on 2026-04-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0002_manualoutboundorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualoutboundorder',
            name='remark',
            field=models.TextField(default='', verbose_name='备注说明'),
        ),
        migrations.AlterField(
            model_name='manualoutboundorder',
            name='reason',
            field=models.CharField(choices=[('urgent', '紧急出库'), ('system_issue', '系统原因暂时无法出库'), ('no_code', '物料编码暂未确定'), ('transfer', '借调物资'), ('off_book', '帐外物资')], default='urgent', max_length=20, verbose_name='手工领料的原因'),
        ),
    ]
