# Generated by Django 6.0.4 on 2026-04-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0003_manualoutboundorder_remark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='编码')),
                ('label', models.CharField(max_length=100, verbose_name='名称')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '领料原因',
                'verbose_name_plural': '领料原因',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AlterField(
            model_name='manualoutboundorder',
            name='reason',
            field=models.CharField(default='urgent', max_length=20, verbose_name='手工领料的原因'),
        ),
    ]
