# Generated by Django 6.0.4 on 2026-04-29 18:21

from django.db import migrations


def seed_default_reasons(apps, schema_editor):
    Reason = apps.get_model('outbound', 'Reason')
    defaults = [
        ('urgent', '紧急出库', 1),
        ('system_issue', '系统原因暂时无法出库', 2),
        ('no_code', '物料编码暂未确定', 3),
        ('transfer', '借调物资', 4),
        ('off_book', '帐外物资', 5),
    ]
    for code, label, sort_order in defaults:
        Reason.objects.get_or_create(
            code=code, defaults={'label': label, 'sort_order': sort_order}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0004_add_reason_model'),
    ]

    operations = [
        migrations.RunPython(seed_default_reasons),
    ]
