# Generated by Django 6.0.4 on 2026-04-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0005_seed_default_reasons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(max_length=50, unique=True, verbose_name='物料编码')),
                ('material_name', models.CharField(db_index=True, max_length=200, verbose_name='物料描述')),
                ('specification', models.CharField(blank=True, default='', max_length=200, verbose_name='规格')),
                ('unit', models.CharField(blank=True, default='', max_length=20, verbose_name='单位')),
            ],
            options={
                'verbose_name': '物料',
                'verbose_name_plural': '物料',
                'ordering': ['material_code'],
            },
        ),
    ]
