# Generated by Django 6.0.4 on 2026-05-21 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0007_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='manualoutboundorder',
            name='void_reason',
            field=models.TextField(blank=True, default='', verbose_name='作废原因'),
        ),
        migrations.AddField(
            model_name='manualoutboundorder',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='作废时间'),
        ),
        migrations.AddField(
            model_name='manualoutboundorder',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voided_orders', to=settings.AUTH_USER_MODEL, verbose_name='作废人'),
        ),
        migrations.AlterField(
            model_name='manualoutboundorder',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('voided', '已作废')], default='draft', max_length=10, verbose_name='单据状态'),
        ),
    ]
