# Generated by Django 6.0.4 on 2026-05-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0008_manualoutboundorder_void_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualoutboundorder',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('completed', '已完成'), ('voided', '已作废')], default='draft', max_length=10, verbose_name='单据状态'),
        ),
    ]
